UnitOfWork implementation
Dalival/Itechart.Internship pull request #3
Opened 2021-07-15 12:01 UTC by Dalival

Third pull request

2021-07-16 07:32 UTC, anton-klokau requested changes

2021-07-16 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/IUnitOfWork.cs
> +         IRepository<TEntity> GetRepository<TEntity>()
fix codestyle

2021-07-16 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/UnitOfWork.cs
> +                return existedRepository as IRepository<TEntity>;
is it safe to cast like this ?

2021-07-16 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/UnitOfWork.cs
> +        private readonly Dictionary<Type, object> _repositories;
any mechanism to use custom repositories ?

2021-07-16 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/IRepository.cs
> +        Task<T> GetByIdAsync(int id);
add new line here and below

2021-07-16 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/Repository.cs
> +        public async Task<T> GetByIdAsync(int id)
is int universal type for id ? is primary key constructed one column ?

2021-07-16 07:32 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/CounterService.cs
> +
fix codestyle

2021-07-16 07:32 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Models/ErrorViewModel.cs
> +
remove whitespaces

2021-07-16 07:32 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Startup.cs
> +            AddMapper(services);
remove automapper

2021-07-16 07:32 UTC, anton-klokau commented
remove base models diff

2021-07-18 11:00 UTC, Dalival commented on src/ITechArt/ITechArt.Repositories/IRepository.cs
> +        Task<T> GetAsync(params object[] keyValues);
Task<IReadOnlyCollection<T>> FindAsync<T>(Expression<Func<T, bool>> expression);

2021-07-18 11:01 UTC, Dalival commented on src/ITechArt/ITechArt.Repositories/IRepository.cs
> +        Task<T> GetAsync(params object[] keyValues);
```suggestion
        Task<IReadOnlyCollection> FindAsync(Expression<Func<T, bool>> expression);
```

2021-07-18 11:02 UTC, Dalival commented on src/ITechArt/ITechArt.Repositories/IRepository.cs
> +        Task<T> GetAsync(params object[] keyValues);
```suggestion
            Task<IReadOnlyCollection<T>> FindAsync<T>(Expression<Func<T, bool>> expression);
```

2021-07-20 08:10 UTC, Verbon commented
1. Itechart.Repositories - move interfaces & implementation to separate folders
2. Repository - should not be disposable, keyValues - rename, GetAsync - GetByIdAsync; code-styles (.ctor - dependency/state fields)
3. UnitOfWork - either implement disposable pattern (recommended), or remove ?. operator (Context?.Dispose();), private TContext Context { get; } - convert to field; code-styles; get rid of Context.GetService<IRepository<TEntity>>(), add extension mechanism to support custom repository types based on Type type (use reflection)
4. SurveysDbContext - code-styles (spaces)
5. HomeController - code-styles

2021-07-22 08:31 UTC, Verbon commented
1. UnitOfWork - GetCustomRepository move implementation to GetRepository; change RegisterCustomRepositories implementation to fill custom repository type mappings (see further), don't forget about strong typing; introduce entity type to custom repository type mapping
2. UnitOfWork<TContext> - code-styles; !_disposed && disposing -> split; _repositories?.Clear(); - do wee need ?. here?
3. SurveysDbContext  - optionsBuilder.UseLazyLoadingProxies(); - figure out whether you really need it?; DbSet<Counter> -> onModeCreating { modelBuilder.... }

2021-07-26 07:32 UTC, anton-klokau requested changes

2021-07-26 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/Interfaces/IRepository.cs
> +        void Add(params T[] entities);
rename Add -> AddRange

parameters should be IReadonlyCollection

same for update/delete

2021-07-26 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/Interfaces/IUnitOfWork.cs
> +            where TEntity : class
fix generic params constraints order (in this case generic params order should be fixed)

2021-07-26 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/Interfaces/IUnitOfWork.cs
> +        void RegisterRepository<TRepository, TEntity>()
should be removed from interface

2021-07-26 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/UnitOfWork.cs
> +        private readonly Dictionary<Type, object> _customRepositories;
fix codestyle, add new line

2021-07-26 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/UnitOfWork.cs
> +            if (_customRepositories.ContainsKey(type))
check TryGetValue method, looks like it is more attractive

same below

2021-07-26 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/UnitOfWork.cs
> +            if (!_repositories.ContainsKey(type))
maybe use TryGetValue ?

rethink repository addition and return

use dictionary methods to mutate collection

2021-07-26 07:32 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/UnitOfWork.cs
> +            _customRepositories[entityType] = Activator.CreateInstance(repositoryType, _context);
use dictionary method to add instance

think about lazy custom repository creation

2021-07-27 07:13 UTC, anton-klokau requested changes

2021-07-27 07:13 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/UnitOfWork.cs
> +        private readonly Dictionary<Type, object> _customRepositories;
redundant dictionary
think about using only one collection

2021-07-27 07:13 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/CounterService.cs
> +            var counter = new Counter();
potential performance issue
what if created counter isn't needed at all ?

2021-07-27 07:13 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/CounterService.cs
> +            if (counters.Any())
think about using FirstOrDefault instead of Any + First

2021-07-27 07:13 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Models/CounterViewModel.cs
> +        public int CounterValue { get; set; }
```suggestion
        public int Value { get; set; }
```

2021-07-27 09:38 UTC, anton-klokau approved these changes

2021-07-27 09:38 UTC, merged