Feature/user table view
Dalival/Itechart.Internship pull request #7
Opened 2021-09-19 10:22 UTC by Dalival

2021-09-20 07:30 UTC, anton-klokau requested changes

2021-09-20 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/UserService.cs
> +            _userRepository = (UserRepository)unitOfWork.GetRepository<User>();
```suggestion
            _userRepository = (UserRepository) unitOfWork.GetRepository<User>();
```

2021-09-20 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/UserService.cs
> +            _userRepository = (UserRepository)unitOfWork.GetRepository<User>();
move cast to UoW

2021-09-20 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Controllers/UserController.cs
> +            var users = await _userService.GetUsersRangeAsync(5, 5 * (page - 1));
declare page size as constant
page - 1 is normalized page value, move to variable

2021-09-20 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Controllers/UserController.cs
> +                    Role = u.UserRoles.Any(ur => ur.Role.Name != "User")
just join roles
remove user role link from admin

2021-09-20 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Controllers/UserController.cs
> +                TotalUsersAmount = await _userService.CountUsersAsync()
await into separate variable

2021-09-20 07:56 UTC, anton-klokau requested changes

2021-09-20 07:56 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Repositories/UnitOfWork.cs
> +    public class UnitOfWork : UnitOfWork<SurveysDbContext>
```suggestion
    public class SurveysUnitOfWork : UnitOfWork<SurveysDbContext>
```

2021-09-20 08:14 UTC, anton-klokau requested changes

2021-09-20 08:14 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Repositories/Repositories/UserRepository.cs
> +        public async Task<IReadOnlyCollection<User>> GetAllIncludeRolesAsync()
```suggestion
        public async Task<IReadOnlyCollection<User>> GetAllWithRolesAsync()
```

2021-09-20 08:14 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Repositories/Repositories/UserRepository.cs
> +        public async Task<IReadOnlyCollection<User>> GetRangeIncludeRolesAsync(int amount, int fromPosition = 0)
```suggestion
        public async Task<IReadOnlyCollection<User>> GetPaginatedAsync(int fromPosition, int amount)
```

2021-09-20 08:14 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Repositories/Repositories/UserRepository.cs
> +        public async Task<IReadOnlyCollection<User>> GetAllIncludeRolesAsync()
GetAll from base repo can be overriden

2021-09-20 08:14 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Repositories/Repositories/UserRepository.cs
> +        public async Task<IReadOnlyCollection<User>> GetRangeIncludeRolesAsync(int amount, int fromPosition = 0)
GetPaginated can be created in base repo and overriden here

2021-09-20 08:14 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Repositories/Repositories/UserRepository.cs
> +        public UserRepository(DbContext dbContext) : base(dbContext) { }
fix codestyles

2021-09-21 13:13 UTC, Dalival commented on src/ITechArt.Surveys/ITechArt.Surveys.Repositories/Repositories/UserRepository.cs
> +        public async Task<IReadOnlyCollection<User>> GetAllIncludeRolesAsync()
I should leave details in name of method to make it clear what does it do.

2021-09-22 07:19 UTC, anton-klokau requested changes

2021-09-22 07:19 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/UserService.cs
> +        private readonly UserRepository _userRepository;
use interfaces instead of classes

2021-09-22 07:19 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Repositories/ISurveysUnitOfWork.cs
> +        UserRepository UserRepository { get; }
use interface instead of class

2021-09-22 07:19 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Repositories/Repositories/UserRepository.cs
> +    public class UserRepository : Repository<User>
add interface inheritance

2021-09-22 07:19 UTC, anton-klokau commented on src/ITechArt/ITechArt.Repositories/Repository.cs
> +            List<T> target;
can be simplified
same below

2021-09-22 12:57 UTC, anton-klokau approved these changes

2021-09-22 12:57 UTC, merged