Feature/delete users
Dalival/Itechart.Internship pull request #8
Opened 2021-09-23 04:12 UTC by Dalival

2021-09-23 07:12 UTC, anton-klokau requested changes

2021-09-23 07:12 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/Interfaces/IUserService.cs
> +        Task<OperationResult<UserManagementError>>  DeleteUserAsync(string id);
OperationResult should be moved to Common

2021-09-23 07:12 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/UserService.cs
> +            var user = await _userRepository.GetByIdAsync(id);
validate user existance

2021-09-24 07:30 UTC, anton-klokau requested changes

2021-09-24 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/UserService.cs
> +                return OperationResult<UserManagementError>.Failed(UserManagementError.CannotDeleteUser);
it is not error with user deletion - user not found
also maybe user don't need to know about user unexistence

2021-09-24 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.Foundation/UserService.cs
> +        public async Task<OperationResult<UserManagementError>> DeleteUserAsync(string id)
use boolean instead of operation result since it contains only one value

2021-09-24 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Models/UserDataForTable.cs
>      public class UserDataForTable
```suggestion
    public class UserDataForTableViewModel
```

2021-09-24 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Controllers/UserController.cs
>                      Role = string.Join(", ", u.UserRoles.Select(ur => ur.Role.Name))
view should be responsive for rendering

2021-09-24 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Controllers/UserController.cs
> +        [HttpGet]
it is not operation for get

*investigate other HTTP verbs

2021-09-24 07:30 UTC, anton-klokau commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Views/User/UserTable.cshtml
> +                    <a href="/User/DeleteUser?id=@user.Id">
id shouldn't be passed as query

2021-09-28 07:21 UTC, Dalival commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Controllers/UserController.cs
> +        [HttpGet]
I've learned HTTP verbs. It's work for HttpPost / HttpDelete. But we can't put Id in request body.

2021-09-28 07:22 UTC, Dalival commented on src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Views/User/UserTable.cshtml
> +                    <a href="/User/DeleteUser?id=@user.Id">
Don't know how to put Id in request body

2021-09-28 07:25 UTC, anton-klokau approved these changes

2021-09-28 07:25 UTC, merged